### ISSUE TITLE
图片生成的七牛域名无效

### ISSUE THREAD

**Issue by yimogit** [52cik/mockjs-lite#1]
七牛云的域名已经无法使用

![image](https://user-images.githubusercontent.com/15975059/48174678-f525a880-e343-11e8-8c97-497a48750018.png)

详情见公告：https://developer.qiniu.com/fusion/kb/1319/test-domain-access-restriction-rules

忘有时间处理下，感谢。

**Comment by 52cik** [comment]
已经更换成 placehold.it
